# Generated by Django 2.1.5 on 2019-02-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0034_auto_20201007_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='t-shirt',
            new_name='tshirt',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='jub-badge',
            new_name='jubbadge',
        ),
    ]
