# Generated by Django 2.1.5 on 2019-02-15 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LedenAdministratie', '0035_auto_20201008_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='speltak',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='mobiel',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='mobiel_ouder1',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='mobiel_ouder2',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='email_ouder1',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='email_ouder2',
            field=models.CharField(max_length=40),
        ),
        migrations.AddField(
            model_name='member',
            name='opmerkingen',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='bijzonderheden',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='member',
            name='inschrijf_datum_sn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RenameField(
            model_name='member',
            old_name='tshirt',
            new_name='tshirt_maat',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='jubbadge',
            new_name='jub_badge',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='verzekering',
            new_name='verzekering_nr',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='foto_publiek',
            new_name='fotopubliek',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='foto_intern',
            new_name='fotobinnen',
        ),
    ]
